import type { Strategy } from '@/types';

// ─── Full strategy catalog — 92 exercises ─────────────────────────────────
// Sourced directly from Anti-Planner PDFs (Vol 1, 2, 3).
// Descriptions are verbatim from PDF content, not invented.
// scope: volume number — used to filter by user's chosen depth (min/mid/all)

export const STRATEGIES: Strategy[] = [

  // ════════════════════════════════════════════════════════════════
  // STUCK — 1.x Difficulty Getting Started
  // ════════════════════════════════════════════════════════════════

  // 1.1 — Difficulty Getting Started
  {
    id: 'stuck-hit-list',
    title: 'Procrastination Hit List',
    feeling: 'stuck',
    subCategory: 'Difficulty Getting Started',
    volume: 1,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Draw your most-avoided tasks as cartoon villains on Wanted posters and knock them out one by one. Messy doodles welcome.',
    traitBoost: ['adhd', 'avoidance', 'boredom'],
  },
  {
    id: 'stuck-heads-tails',
    title: 'Heads or Tails',
    feeling: 'stuck',
    subCategory: 'Difficulty Getting Started',
    volume: 1,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Flip a coin per task. Heads = do it today. Tails = guilt-free procrastination. 50/50 chance of a break.',
    traitBoost: ['adhd', 'avoidance', 'executive'],
  },
  {
    id: 'stuck-roadblocks',
    title: 'Identify Roadblocks',
    feeling: 'stuck',
    subCategory: 'Difficulty Getting Started',
    volume: 1,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Map what consistently gets between you and your goals, then brainstorm workarounds you\'d actually try — not willpower, smarter systems.',
    traitBoost: ['executive', 'perfectionism', 'adhd'],
  },
  {
    id: 'stuck-music-challenge',
    title: 'Music Challenge',
    feeling: 'stuck',
    subCategory: 'Difficulty Getting Started',
    volume: 2,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Race a song, album, or playlist. See how much you can get done before it ends. When the music stops, you stop.',
    traitBoost: ['adhd', 'boredom', 'avoidance'],
  },
  {
    id: 'stuck-task-adjacency',
    title: 'Task Adjacency',
    feeling: 'stuck',
    subCategory: 'Difficulty Getting Started',
    volume: 2,
    tag: 'quick',
    tagLabel: 'quick win',
    desc: 'Start with something near the task — not the task itself. Do the tangentially-related thing and let proximity do the rest.',
    traitBoost: ['avoidance', 'executive', 'adhd'],
  },
  {
    id: 'stuck-body-doubling',
    title: 'Body-Doubling',
    feeling: 'stuck',
    subCategory: 'Difficulty Getting Started',
    volume: 3,
    tag: 'quick',
    tagLabel: 'quick win',
    desc: 'Work alongside someone — in person, on video, or a study-with-me stream. Neutral presence = focus.',
    traitBoost: ['adhd', 'boredom', 'executive'],
  },
  {
    id: 'stuck-verbal-processing',
    title: 'Verbal Processing',
    feeling: 'stuck',
    subCategory: 'Difficulty Getting Started',
    volume: 3,
    tag: 'quick',
    tagLabel: 'quick win',
    desc: 'Tell someone exactly what you\'re about to do before you start. Articulating the plan out loud activates a different part of your brain.',
    traitBoost: ['executive', 'adhd', 'avoidance'],
  },

  // 1.2 — Indecisive
  {
    id: 'stuck-pros-cons',
    title: 'Pros & Cons List',
    feeling: 'stuck',
    subCategory: 'Indecisive',
    volume: 1,
    tag: 'organize',
    tagLabel: 'organize',
    desc: 'Write pros and cons, assign point values by importance, tally up. Highest score wins — decision made.',
    traitBoost: ['anxiety', 'perfectionism', 'executive'],
  },
  {
    id: 'stuck-fortune-teller',
    title: 'Fortune Teller',
    feeling: 'stuck',
    subCategory: 'Indecisive',
    volume: 1,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Make a paper fortune teller, write in your tasks, let it pick what you do next. A throwback that actually works.',
    traitBoost: ['adhd', 'boredom', 'avoidance'],
  },
  {
    id: 'stuck-dice-roll',
    title: 'Dice Roll',
    feeling: 'stuck',
    subCategory: 'Indecisive',
    volume: 2,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Roll a die to determine which task to start. Chance removes the paralysis. Works with a 20-sided or standard die.',
    traitBoost: ['adhd', 'anxiety', 'avoidance'],
  },
  {
    id: 'stuck-decisions-faster',
    title: 'How To Make Decisions Faster',
    feeling: 'stuck',
    subCategory: 'Indecisive',
    volume: 2,
    tag: 'mindset',
    tagLabel: 'mindset',
    desc: 'A guide to cutting through analysis paralysis: set your success criteria, trust your gut, and know when to stop researching.',
    traitBoost: ['perfectionism', 'anxiety', 'executive'],
  },
  {
    id: 'stuck-coin-spin',
    title: 'Coin Spin',
    feeling: 'stuck',
    subCategory: 'Indecisive',
    volume: 3,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Spin a coin on a grid of tasks. Where it lands, that\'s where you start. Chance of guilt-free delay built in.',
    traitBoost: ['adhd', 'avoidance', 'boredom'],
  },

  // 1.3 — Perfectionistic
  {
    id: 'stuck-half-ass',
    title: 'How To Half-Ass It',
    feeling: 'stuck',
    subCategory: 'Perfectionistic',
    volume: 1,
    tag: 'mindset',
    tagLabel: 'mindset',
    desc: 'Separate must-haves (can\'t be "done" without them) from nice-to-haves (add if you have extra time). Finish the musts first.',
    traitBoost: ['perfectionism', 'anxiety', 'overwhelm'],
  },
  {
    id: 'stuck-realistic-expectations',
    title: 'Set Realistic Expectations',
    feeling: 'stuck',
    subCategory: 'Perfectionistic',
    volume: 1,
    tag: 'mindset',
    tagLabel: 'mindset',
    desc: 'Set your bar low. Focus on a baby step that\'s better than nothing. Getting started is usually the hardest part.',
    traitBoost: ['perfectionism', 'anxiety', 'shame'],
  },
  {
    id: 'stuck-inbox-sprint',
    title: 'Inbox Sprint',
    feeling: 'stuck',
    subCategory: 'Perfectionistic',
    volume: 2,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Set a 30-minute timer and answer as many emails as possible. Speed over perfection — how many can you clear?',
    traitBoost: ['perfectionism', 'adhd', 'boredom'],
  },
  {
    id: 'stuck-speed-run',
    title: 'Speed Run',
    feeling: 'stuck',
    subCategory: 'Perfectionistic',
    volume: 2,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Set a short timer (5–15 mins), speed through one task as fast as you can without trying to make it perfect. Stop when it goes off.',
    traitBoost: ['perfectionism', 'adhd', 'boredom'],
  },
  {
    id: 'stuck-timer-challenge',
    title: 'Timer Challenge',
    feeling: 'stuck',
    subCategory: 'Perfectionistic',
    volume: 3,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Set a time limit per step of a task. Stack them up, see how fast they total — and race the clock.',
    traitBoost: ['perfectionism', 'adhd', 'executive'],
  },

  // 1.4 — Distracted
  {
    id: 'stuck-distractions-list',
    title: 'Distractions List',
    feeling: 'stuck',
    subCategory: 'Distracted',
    volume: 1,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Name your actual distractions — apps, people, hunger, noise — then brainstorm workarounds you\'d genuinely try.',
    traitBoost: ['adhd', 'executive', 'boredom'],
  },
  {
    id: 'stuck-time-wasters',
    title: 'Top 5 Time Wasters',
    feeling: 'stuck',
    subCategory: 'Distracted',
    volume: 1,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Identify your top 5 time-wasting apps, activities, and people, then pick a difficulty level and start tackling them.',
    traitBoost: ['adhd', 'avoidance', 'boredom'],
  },
  {
    id: 'stuck-stop-screens',
    title: 'How To Stop Getting Distracted By Screens',
    feeling: 'stuck',
    subCategory: 'Distracted',
    volume: 2,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'A tiered challenge system for breaking screen habits — Easy to Legendary. Pick your difficulty and work up.',
    traitBoost: ['adhd', 'avoidance', 'boredom'],
  },
  {
    id: 'stuck-idea-parking-lot',
    title: 'Idea Parking Lot',
    feeling: 'stuck',
    subCategory: 'Distracted',
    volume: 2,
    tag: 'organize',
    tagLabel: 'organize',
    desc: 'Create a dedicated space for ideas that pop up mid-task. Write them down and release them — your brain empties, your focus stays.',
    traitBoost: ['adhd', 'executive', 'boredom'],
  },
  {
    id: 'stuck-dream-workstation',
    title: 'Dream Workstation',
    feeling: 'stuck',
    subCategory: 'Distracted',
    volume: 3,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Draw or write your ideal work setup: the place, the clothes, the supplies, the snack. Then start building toward it.',
    traitBoost: ['adhd', 'executive', 'boredom'],
  },
  {
    id: 'stuck-focus-mixtape',
    title: 'Focus Mixtape',
    feeling: 'stuck',
    subCategory: 'Distracted',
    volume: 3,
    tag: 'tool',
    tagLabel: 'tool',
    desc: 'Build a playlist of songs you can put on repeat without getting distracted by them. Keep it for focus sessions only.',
    traitBoost: ['adhd', 'boredom', 'executive'],
  },

  // ════════════════════════════════════════════════════════════════
  // OVERWHELMED — 2.x
  // ════════════════════════════════════════════════════════════════

  // 2.1 — Intimidated
  {
    id: 'ow-visualization',
    title: 'Fast-Forward Visualization',
    feeling: 'overwhelmed',
    subCategory: 'Intimidated',
    volume: 1,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Close your eyes. Play the whole task through in your head like a fast-forward movie — every step, start to finish.',
    traitBoost: ['anxiety', 'perfectionism', 'adhd'],
  },
  {
    id: 'ow-task-breakdown',
    title: 'Task Breakdown',
    feeling: 'overwhelmed',
    subCategory: 'Intimidated',
    volume: 1,
    tag: 'organize',
    tagLabel: 'organize',
    desc: 'Break one intimidating task into all its steps, then break those into smaller actions, until everything on the list feels doable.',
    traitBoost: ['executive', 'perfectionism', 'overwhelm'],
  },
  {
    id: 'ow-batching',
    title: 'Batching',
    feeling: 'overwhelmed',
    subCategory: 'Intimidated',
    volume: 2,
    tag: 'organize',
    tagLabel: 'organize',
    desc: 'Group repetitive steps across multiple tasks and do them all in one pass. Fewer gear-shifts = more done.',
    traitBoost: ['executive', 'adhd', 'overwhelm'],
  },
  {
    id: 'ow-break-down-tasks',
    title: 'How To Break Down Tasks',
    feeling: 'overwhelmed',
    subCategory: 'Intimidated',
    volume: 2,
    tag: 'organize',
    tagLabel: 'organize',
    desc: 'A step-by-step guide to turning a vague, overwhelming task into a concrete roadmap — envision done, write main steps, pull them apart.',
    traitBoost: ['executive', 'anxiety', 'overwhelm'],
  },
  {
    id: 'ow-intimidation-reframing',
    title: 'Intimidation Reframing',
    feeling: 'overwhelmed',
    subCategory: 'Intimidated',
    volume: 3,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Name the emotions making a task feel scary, then actively look for a different way to interpret each one.',
    traitBoost: ['anxiety', 'shame', 'perfectionism'],
  },
  {
    id: 'ow-pomodoro',
    title: 'Pomodoro Timers',
    feeling: 'overwhelmed',
    subCategory: 'Intimidated',
    volume: 3,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Work in short timed bursts with breaks in between. Small chunks of progress on something you\'ve been avoiding beat none.',
    traitBoost: ['adhd', 'avoidance', 'overwhelm'],
  },
  {
    id: 'ow-time-estimation',
    title: 'Time Estimation Challenge',
    feeling: 'overwhelmed',
    subCategory: 'Intimidated',
    volume: 3,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Guess how long a task will take, then time yourself doing it. Reality is almost always faster than the dread makes it seem.',
    traitBoost: ['anxiety', 'perfectionism', 'adhd'],
  },

  // 2.2 — Over-Committed
  {
    id: 'ow-get-out',
    title: 'How To Get Out of Stuff You Don\'t Want To Do',
    feeling: 'overwhelmed',
    subCategory: 'Over-Committed',
    volume: 1,
    tag: 'mindset',
    tagLabel: 'mindset',
    desc: 'Scripts for saying no to social plans, work requests, and general asks — without owing anyone an explanation.',
    traitBoost: ['overwhelm', 'anxiety', 'avoidance'],
  },
  {
    id: 'ow-truth-dare-overcommitted',
    title: 'Truth or Dare: Over-Committed',
    feeling: 'overwhelmed',
    subCategory: 'Over-Committed',
    volume: 1,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Answer a hard truth about who you can\'t say no to and why. Then take the dare: say no to one thing today.',
    traitBoost: ['anxiety', 'avoidance', 'shame'],
  },
  {
    id: 'ow-commitment-list',
    title: 'Commitment List',
    feeling: 'overwhelmed',
    subCategory: 'Over-Committed',
    volume: 2,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Write out every single thing you\'ve said yes to. Then actually look at the list. Overcommitment lives in that gap.',
    traitBoost: ['overwhelm', 'executive', 'anxiety'],
  },
  {
    id: 'ow-realistic-work',
    title: 'Set Realistic Expectations at Work',
    feeling: 'overwhelmed',
    subCategory: 'Over-Committed',
    volume: 3,
    tag: 'mindset',
    tagLabel: 'mindset',
    desc: 'Under-promise, over-deliver. Over-estimate how long things take. Manage expectations before they manage you.',
    traitBoost: ['perfectionism', 'anxiety', 'overwhelm'],
  },

  // 2.3 — Panicked
  {
    id: 'ow-stress-plan',
    title: 'Stress Action Plan',
    feeling: 'overwhelmed',
    subCategory: 'Panicked',
    volume: 1,
    tag: 'organize',
    tagLabel: 'organize',
    desc: 'Map each stressor to at least one concrete action you can take — and when. You can always do something.',
    traitBoost: ['anxiety', 'overwhelm', 'executive'],
  },
  {
    id: 'ow-jumanji',
    title: 'How To Work During Jumanji',
    feeling: 'overwhelmed',
    subCategory: 'Panicked',
    volume: 1,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Pick one task you\'ve been struggling to work on, fill out structured prompts to find your next move. Bonus points for coloring.',
    traitBoost: ['overwhelm', 'anxiety', 'adhd'],
  },
  {
    id: 'ow-anxiety-vent',
    title: 'Anxiety Vent Space',
    feeling: 'overwhelmed',
    subCategory: 'Panicked',
    volume: 2,
    tag: 'quick',
    tagLabel: 'quick win',
    desc: 'Write down every stressed-out thought swirling in your brain. Get it out of your head and onto paper.',
    traitBoost: ['anxiety', 'overwhelm', 'adhd'],
  },
  {
    id: 'ow-coloring',
    title: 'AAAHHHH Coloring Page',
    feeling: 'overwhelmed',
    subCategory: 'Panicked',
    volume: 3,
    tag: 'quick',
    tagLabel: 'quick win',
    desc: 'A coloring page for when you need to scream. Color it out first, then deal with the rest.',
    traitBoost: ['anxiety', 'overwhelm', 'adhd'],
  },
  {
    id: 'ow-meditation',
    title: 'Meditation For Newbies',
    feeling: 'overwhelmed',
    subCategory: 'Panicked',
    volume: 3,
    tag: 'mindset',
    tagLabel: 'mindset',
    desc: 'A no-eye-roll intro to meditation for people who hate the idea. Sit, breathe, try it once — that\'s it.',
    traitBoost: ['anxiety', 'overwhelm', 'adhd'],
  },

  // 2.4 — Burnt-Out
  {
    id: 'ow-damn-break',
    title: 'Give Yourself a Damn Break',
    feeling: 'overwhelmed',
    subCategory: 'Burnt-Out',
    volume: 1,
    tag: 'quick',
    tagLabel: 'quick win',
    desc: 'List everything you enjoy but never make time for. Then actually do one. Recharging is not optional.',
    traitBoost: ['overwhelm', 'shame', 'anxiety'],
  },
  {
    id: 'ow-feed-yourself',
    title: 'Ideas To Feed Yourself',
    feeling: 'overwhelmed',
    subCategory: 'Burnt-Out',
    volume: 1,
    tag: 'quick',
    tagLabel: 'quick win',
    desc: 'When you\'re too burnt out to cook, here\'s the full no-effort meal list. Grab-and-go, microwave, toaster. Eating something is non-negotiable.',
    traitBoost: ['overwhelm', 'executive', 'adhd'],
  },
  {
    id: 'ow-ask-help',
    title: 'How To Ask For Help',
    feeling: 'overwhelmed',
    subCategory: 'Burnt-Out',
    volume: 2,
    tag: 'mindset',
    tagLabel: 'mindset',
    desc: 'Scripts and tips for asking for support when you\'re drowning. It really isn\'t as scary as it feels.',
    traitBoost: ['anxiety', 'shame', 'avoidance'],
  },
  {
    id: 'ow-signs-burnout',
    title: 'Signs Of Burnout',
    feeling: 'overwhelmed',
    subCategory: 'Burnt-Out',
    volume: 2,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'A checklist of physical and emotional burnout symptoms — sleep, appetite, mood, energy. Know what you\'re actually dealing with.',
    traitBoost: ['overwhelm', 'anxiety', 'executive'],
  },
  {
    id: 'ow-selfcare-challenge',
    title: 'Self-Care Checklist Challenge',
    feeling: 'overwhelmed',
    subCategory: 'Burnt-Out',
    volume: 3,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'A checklist of real self-care options — not bubble baths and face masks. How many can you check off over time?',
    traitBoost: ['overwhelm', 'boredom', 'avoidance'],
  },

  // ════════════════════════════════════════════════════════════════
  // UNMOTIVATED — 3.x
  // ════════════════════════════════════════════════════════════════

  // 3.1 — Waiting To Feel Like It
  {
    id: 'um-avoidance-bingo',
    title: 'Avoidance Bingo',
    feeling: 'unmotivated',
    subCategory: 'Waiting To Feel Like It',
    volume: 1,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Fill a bingo board with tasks across 5 life categories. Cross them off as you go — get a row, or black out the whole board.',
    traitBoost: ['adhd', 'boredom', 'avoidance'],
  },
  {
    id: 'um-avoidance-log',
    title: 'Avoidance Log',
    feeling: 'unmotivated',
    subCategory: 'Waiting To Feel Like It',
    volume: 1,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Write out exactly what you\'re avoiding, your anxiety level, every fear making it worse, and your single smallest first step.',
    traitBoost: ['avoidance', 'anxiety', 'executive'],
  },
  {
    id: 'um-blackjack',
    title: 'Procrastination Blackjack',
    feeling: 'unmotivated',
    subCategory: 'Waiting To Feel Like It',
    volume: 1,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Flip cards and add up the score. Under 21 determines how many tasks you do. Hit exactly 21 and you\'re off the hook entirely.',
    traitBoost: ['adhd', 'boredom', 'avoidance'],
  },
  {
    id: 'um-excuse-list',
    title: 'Excuse List',
    feeling: 'unmotivated',
    subCategory: 'Waiting To Feel Like It',
    volume: 2,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Write down the excuses you tell yourself to avoid tasks. Then write a rebuttal for each one that actually makes sense.',
    traitBoost: ['avoidance', 'anxiety', 'adhd'],
  },
  {
    id: 'um-productive-mood',
    title: 'Get In The Productive Mood',
    feeling: 'unmotivated',
    subCategory: 'Waiting To Feel Like It',
    volume: 2,
    tag: 'mindset',
    tagLabel: 'mindset',
    desc: 'Build a sensory ritual that signals "it\'s work time" to your brain — a specific scent, outfit, location, or song.',
    traitBoost: ['adhd', 'executive', 'boredom'],
  },
  {
    id: 'um-morning-person',
    title: 'How To Trick Yourself Into Becoming A Morning Person',
    feeling: 'unmotivated',
    subCategory: 'Waiting To Feel Like It',
    volume: 2,
    tag: 'tool',
    tagLabel: 'tool',
    desc: 'A 3-alarm system that builds in guilt-free snooze and phone time so mornings stop feeling like punishment.',
    traitBoost: ['adhd', 'executive', 'avoidance'],
  },
  {
    id: 'um-suit-up',
    title: 'Suit Up Card Game',
    feeling: 'unmotivated',
    subCategory: 'Waiting To Feel Like It',
    volume: 2,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Draw 4 cards. Each suit maps to a task category; each number sets the time. Pick one card — that\'s what you do.',
    traitBoost: ['adhd', 'boredom', 'avoidance'],
  },
  {
    id: 'um-switch-it-up',
    title: 'Switch It Up',
    feeling: 'unmotivated',
    subCategory: 'Waiting To Feel Like It',
    volume: 3,
    tag: 'quick',
    tagLabel: 'quick win',
    desc: 'Pick a different place to work and go there. Commit to a place, a task, and a time you\'ll be done. New environment, new brain.',
    traitBoost: ['adhd', 'boredom', 'avoidance'],
  },

  // 3.2 — Lacking Accountability
  {
    id: 'um-bet-ya-cant',
    title: 'Bet-Ya-Can\'t Board',
    feeling: 'unmotivated',
    subCategory: 'Lacking Accountability',
    volume: 1,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Draw the person or voice that doubts you. Give them a speech bubble. Then do the thing and prove them wrong.',
    traitBoost: ['adhd', 'boredom', 'avoidance'],
  },
  {
    id: 'um-task-battle',
    title: 'Task Battle',
    feeling: 'unmotivated',
    subCategory: 'Lacking Accountability',
    volume: 1,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Play battleship with a friend using your to-do lists as the hidden grid. If they hit your square, you have to do that task next.',
    traitBoost: ['adhd', 'boredom', 'avoidance'],
  },
  {
    id: 'um-accountability-betting',
    title: 'Accountability Betting',
    feeling: 'unmotivated',
    subCategory: 'Lacking Accountability',
    volume: 2,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Put something on the line with a trusted person, get it in writing, set a deadline. Loss aversion is a powerful motivator.',
    traitBoost: ['avoidance', 'adhd', 'anxiety'],
  },
  {
    id: 'um-creating-accountability',
    title: 'Creating Accountability',
    feeling: 'unmotivated',
    subCategory: 'Lacking Accountability',
    volume: 2,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Identify what\'s made you follow through in the past — last-minute panic, external pressure, rewards — then deliberately re-create it.',
    traitBoost: ['executive', 'avoidance', 'adhd'],
  },
  {
    id: 'um-grime-punishment',
    title: 'Grime & Punishment',
    feeling: 'unmotivated',
    subCategory: 'Lacking Accountability',
    volume: 3,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Make a contract: if you don\'t do the thing, you do the chore you hate most. Stakes are real and consequences are specific.',
    traitBoost: ['avoidance', 'boredom', 'adhd'],
  },

  // 3.3 — Disinterested
  {
    id: 'um-treat-yo-self',
    title: 'Treat Yo Self',
    feeling: 'unmotivated',
    subCategory: 'Disinterested',
    volume: 1,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Build "after I do X, I get Y" reward contracts using things that actually motivate you. Match the size of the reward to the effort.',
    traitBoost: ['adhd', 'boredom', 'avoidance'],
  },
  {
    id: 'um-worst-tasks',
    title: 'Worst Tasks Ever',
    feeling: 'unmotivated',
    subCategory: 'Disinterested',
    volume: 1,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Write out why a task is genuinely terrible — then brainstorm one thing that might make it even slightly less miserable.',
    traitBoost: ['avoidance', 'boredom', 'executive'],
  },
  {
    id: 'um-truth-dare-disinterested',
    title: 'Truth or Dare: Disinterested',
    feeling: 'unmotivated',
    subCategory: 'Disinterested',
    volume: 2,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Answer a hard truth about how you\'ve gotten through tasks you hated before. Then take the dare: try a new approach for three days.',
    traitBoost: ['boredom', 'avoidance', 'adhd'],
  },
  {
    id: 'um-complaint-form',
    title: 'Task Complaint Form',
    feeling: 'unmotivated',
    subCategory: 'Disinterested',
    volume: 3,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'File an official complaint about the task you\'re avoiding — every grievance, however petty. Get it all out. Then do it anyway.',
    traitBoost: ['avoidance', 'adhd', 'anxiety'],
  },

  // 3.4 — Uninspired
  {
    id: 'um-goals-dont-suck',
    title: 'Setting Goals That Don\'t Suck',
    feeling: 'unmotivated',
    subCategory: 'Uninspired',
    volume: 1,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Map a goal across 7 questions: what you want, why it matters, what it takes, what success looks like, how it feels, what\'s in the way, how you\'ll keep going.',
    traitBoost: ['executive', 'avoidance', 'shame'],
  },
  {
    id: 'um-pump-up-mixtape',
    title: 'Pump-Up Mixtape',
    feeling: 'unmotivated',
    subCategory: 'Uninspired',
    volume: 2,
    tag: 'tool',
    tagLabel: 'tool',
    desc: 'Build a playlist of songs that make you feel unstoppable. Play it before you start — not during, before.',
    traitBoost: ['adhd', 'boredom', 'avoidance'],
  },
  {
    id: 'um-role-models',
    title: 'Top 5 Role Models',
    feeling: 'unmotivated',
    subCategory: 'Uninspired',
    volume: 2,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Write down 5 people you admire and exactly why. Reconnect with what inspires you by putting it into words.',
    traitBoost: ['shame', 'anxiety', 'avoidance'],
  },
  {
    id: 'um-stay-inspired',
    title: 'How To Stay Inspired',
    feeling: 'unmotivated',
    subCategory: 'Uninspired',
    volume: 3,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Identify the specific things that reliably re-ignite you — and build a plan to use them when you\'re running on empty.',
    traitBoost: ['adhd', 'boredom', 'shame'],
  },
  {
    id: 'um-truth-dare-uninspired',
    title: 'Truth or Dare: Uninspired',
    feeling: 'unmotivated',
    subCategory: 'Uninspired',
    volume: 3,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Describe your ideal life and who you\'d need to become to live it. Then take the dare: find a motivational video and watch it.',
    traitBoost: ['boredom', 'shame', 'avoidance'],
  },

  // ════════════════════════════════════════════════════════════════
  // DISORGANIZED — 4.x
  // ════════════════════════════════════════════════════════════════

  // 4.1 — Messy
  {
    id: 'dis-design-environment',
    title: 'Design Your Environment',
    feeling: 'disorganized',
    subCategory: 'Messy',
    volume: 1,
    tag: 'organize',
    tagLabel: 'organize',
    desc: 'Map where things consistently end up vs. where they\'re supposed to go. Build a system around reality, not theory.',
    traitBoost: ['executive', 'adhd', 'overwhelm'],
  },
  {
    id: 'dis-clean-by-numbers',
    title: 'Clean By Numbers',
    feeling: 'disorganized',
    subCategory: 'Messy',
    volume: 2,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Assign a color to each area of your space. Clean it, unlock that color, fill it in. Cleaning reveals a hidden picture.',
    traitBoost: ['adhd', 'boredom', 'executive'],
  },
  {
    id: 'dis-speed-clean',
    title: 'How To Speed-Clean',
    feeling: 'disorganized',
    subCategory: 'Messy',
    volume: 2,
    tag: 'organize',
    tagLabel: 'organize',
    desc: 'Before photo → trash bag → clothes to hamper → dishes to kitchen → surfaces. A step-by-step protocol, no overthinking.',
    traitBoost: ['executive', 'adhd', 'overwhelm'],
  },
  {
    id: 'dis-scavenger-hunt',
    title: 'Cleaning Scavenger Hunt',
    feeling: 'disorganized',
    subCategory: 'Messy',
    volume: 3,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Find and put away items by color and category — one at a time. Turns tidying into a hunt.',
    traitBoost: ['adhd', 'boredom', 'executive'],
  },
  {
    id: 'dis-fridge-overhaul',
    title: 'Fridge Overhaul Challenge',
    feeling: 'disorganized',
    subCategory: 'Messy',
    volume: 3,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Gloves on, playlist ready. Before photo → expired food out → leftovers gone → wipe shelves. Step by step, nothing skipped.',
    traitBoost: ['executive', 'adhd', 'boredom'],
  },
  {
    id: 'dis-digital-workspace',
    title: 'Organize Your Digital Workspace',
    feeling: 'disorganized',
    subCategory: 'Messy',
    volume: 3,
    tag: 'organize',
    tagLabel: 'organize',
    desc: 'A simple system for taming digital clutter: desktop folders, email labels, and download management — in that order.',
    traitBoost: ['executive', 'adhd', 'overwhelm'],
  },
  {
    id: 'dis-personal-records',
    title: 'Personal Records',
    feeling: 'disorganized',
    subCategory: 'Messy',
    volume: 3,
    tag: 'game',
    tagLabel: 'gamify',
    desc: 'Time yourself on regular tasks and try to beat your own record. Efficiency becomes a competition against yourself.',
    traitBoost: ['adhd', 'boredom', 'executive'],
  },
  {
    id: 'dis-piles-coloring',
    title: 'Piles For Miles (Coloring)',
    feeling: 'disorganized',
    subCategory: 'Messy',
    volume: 3,
    tag: 'quick',
    tagLabel: 'quick win',
    desc: 'A coloring page for when you\'re staring at the pile but can\'t start. Color first, tackle after.',
    traitBoost: ['adhd', 'overwhelm', 'anxiety'],
  },

  // 4.2 — Difficulty Prioritizing
  {
    id: 'dis-labeling',
    title: 'Labeling',
    feeling: 'disorganized',
    subCategory: 'Difficulty Prioritizing',
    volume: 1,
    tag: 'organize',
    tagLabel: 'organize',
    desc: 'Sort your to-do list by category (Contact, Create, Decide, Purchase, Research) instead of listing randomly. Work one category at a time.',
    traitBoost: ['executive', 'adhd', 'overwhelm'],
  },
  {
    id: 'dis-kanban',
    title: 'Kanban Board',
    feeling: 'disorganized',
    subCategory: 'Difficulty Prioritizing',
    volume: 1,
    tag: 'organize',
    tagLabel: 'organize',
    desc: 'Move tasks through To-Do, Doing, On Hold, and Done columns. Visual, satisfying, impossible to lose track.',
    traitBoost: ['executive', 'adhd', 'overwhelm'],
  },
  {
    id: 'dis-rank-that-stuff',
    title: 'Rank That Stuff',
    feeling: 'disorganized',
    subCategory: 'Difficulty Prioritizing',
    volume: 1,
    tag: 'organize',
    tagLabel: 'organize',
    desc: 'Rate every task low / medium / high priority, then rank within each level. Start at #1 and work down.',
    traitBoost: ['executive', 'overwhelm', 'adhd'],
  },
  {
    id: 'dis-priority-worksheet',
    title: 'Priority Worksheet',
    feeling: 'disorganized',
    subCategory: 'Difficulty Prioritizing',
    volume: 2,
    tag: 'organize',
    tagLabel: 'organize',
    desc: 'Score each task on importance (1–5) + urgency (1–5). 8+ = do it now. 1–3 = forget it for today.',
    traitBoost: ['executive', 'overwhelm', 'anxiety'],
  },
  {
    id: 'dis-theme-weeks',
    title: 'Theme Weeks',
    feeling: 'disorganized',
    subCategory: 'Difficulty Prioritizing',
    volume: 2,
    tag: 'mindset',
    tagLabel: 'mindset',
    desc: 'Pick one focus area for the whole week. Do 10 things in that category. Everything else waits. Log only what you\'ve already done.',
    traitBoost: ['adhd', 'executive', 'overwhelm'],
  },
  {
    id: 'dis-eisenhower',
    title: 'Urgent vs. Important Grid',
    feeling: 'disorganized',
    subCategory: 'Difficulty Prioritizing',
    volume: 3,
    tag: 'organize',
    tagLabel: 'organize',
    desc: 'Brain-dump tasks, sort into four quadrants — Do Now, Schedule, Delegate, Drop. Work the top quadrant only.',
    traitBoost: ['executive', 'overwhelm', 'anxiety'],
  },

  // ════════════════════════════════════════════════════════════════
  // DISCOURAGED — 5.x
  // ════════════════════════════════════════════════════════════════

  // 5.1 — Hopeless
  {
    id: 'dc-compassion-pep',
    title: 'Self-Compassion Pep Talk',
    feeling: 'discouraged',
    subCategory: 'Hopeless',
    volume: 1,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Write what\'s upsetting you. Then write what you\'d tell a close friend who came to you with the exact same problem.',
    traitBoost: ['shame', 'anxiety', 'perfectionism'],
  },
  {
    id: 'dc-draw-feels',
    title: 'Draw Your Feels',
    feeling: 'discouraged',
    subCategory: 'Hopeless',
    volume: 2,
    tag: 'quick',
    tagLabel: 'quick win',
    desc: 'Name one emotion. Then draw what it feels like — any medium, any style. No art skills required.',
    traitBoost: ['anxiety', 'shame', 'overwhelm'],
  },
  {
    id: 'dc-ta-da-list',
    title: 'Ta-Da List',
    feeling: 'discouraged',
    subCategory: 'Hopeless',
    volume: 2,
    tag: 'quick',
    tagLabel: 'quick win',
    desc: 'List everything you actually did today. Not a to-do list — a done list. Never add things you haven\'t done yet. Give yourself the credit.',
    traitBoost: ['shame', 'perfectionism', 'anxiety'],
  },
  {
    id: 'dc-forgive-yourself',
    title: 'Forgive Yourself',
    feeling: 'discouraged',
    subCategory: 'Hopeless',
    volume: 3,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Write what you can\'t stop blaming yourself for. Then look at it honestly — is anyone else still thinking about it?',
    traitBoost: ['shame', 'anxiety', 'perfectionism'],
  },
  {
    id: 'dc-not-alone-coloring',
    title: 'I Am Not Alone (Coloring)',
    feeling: 'discouraged',
    subCategory: 'Hopeless',
    volume: 3,
    tag: 'quick',
    tagLabel: 'quick win',
    desc: 'A coloring page for the moments when everything feels isolating. Color it. You\'re not alone in this.',
    traitBoost: ['shame', 'anxiety', 'adhd'],
  },
  {
    id: 'dc-lessons-learned',
    title: 'Lessons Learned',
    feeling: 'discouraged',
    subCategory: 'Hopeless',
    volume: 3,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Look back at your hardest moments and write down what each one taught you. Not to minimize — to find the signal in the noise.',
    traitBoost: ['shame', 'perfectionism', 'anxiety'],
  },

  // 5.2 — Insecure
  {
    id: 'dc-trophy-shelf',
    title: 'Small Wins Trophy Shelf',
    feeling: 'discouraged',
    subCategory: 'Insecure',
    volume: 1,
    tag: 'quick',
    tagLabel: 'quick win',
    desc: 'Log the small things you actually got done — finally made that appointment? That goes on the shelf. It counts.',
    traitBoost: ['shame', 'anxiety', 'perfectionism'],
  },
  {
    id: 'dc-scumbag-brain',
    title: 'Shutting Up Scumbag Brain',
    feeling: 'discouraged',
    subCategory: 'Insecure',
    volume: 2,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Name the mean voice in your head. Give it a ridiculous name. Then tell it where to go every time it shows up.',
    traitBoost: ['shame', 'anxiety', 'perfectionism'],
  },
  {
    id: 'dc-thought-traps',
    title: 'Watch Out For Thought Traps',
    feeling: 'discouraged',
    subCategory: 'Insecure',
    volume: 2,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Learn to recognize your cognitive distortions by name: catastrophizer, all-or-nothing thinker, conclusion jumper. Naming them is the first step to not believing them.',
    traitBoost: ['anxiety', 'shame', 'perfectionism'],
  },
  {
    id: 'dc-insecurity-list',
    title: 'Insecurity List',
    feeling: 'discouraged',
    subCategory: 'Insecure',
    volume: 3,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Write what you feel insecure about, why, and whose judgment you\'re actually afraid of. Patterns emerge when it\'s on paper.',
    traitBoost: ['shame', 'anxiety', 'avoidance'],
  },
  {
    id: 'dc-real-you',
    title: 'Seeing The Real You',
    feeling: 'discouraged',
    subCategory: 'Insecure',
    volume: 3,
    tag: 'reflect',
    tagLabel: 'reflect',
    desc: 'Structured prompts to write down your actual strengths — the ones other people see, even on the days you can\'t.',
    traitBoost: ['shame', 'perfectionism', 'anxiety'],
  },
  {
    id: 'dc-victory-lap',
    title: 'Victory Lap',
    feeling: 'discouraged',
    subCategory: 'Insecure',
    volume: 3,
    tag: 'quick',
    tagLabel: 'quick win',
    desc: 'Build a running list of moments you\'re proud of — big and small. Come back and read it when you forget who you are.',
    traitBoost: ['shame', 'anxiety', 'perfectionism'],
  },
];

// ─── Helpers ───────────────────────────────────────────────────────────────

/** Filter catalog by user's chosen scope */
export function filterByScope(
  strategies: Strategy[],
  scope: 'min' | 'mid' | 'all'
): Strategy[] {
  if (scope === 'all') return strategies;
  if (scope === 'mid') return strategies.filter(s => s.volume <= 2);
  return strategies.filter(s => s.volume === 1);
}

/** Get strategies for a feeling, sorted by:
 *  1. Pinned first
 *  2. Trait boost match count (desc)
 *  3. Worked rating score (desc)
 *  4. Original catalog order
 */
export function getSortedStrategies(
  feeling: string,
  scope: 'min' | 'mid' | 'all',
  traits: string[],
  ratings: Record<string, { worked: number; nope: number }>,
  pinned: string[],
  hidden: string[]
): Strategy[] {
  const pool = filterByScope(STRATEGIES, scope)
    .filter(s => s.feeling === feeling && !hidden.includes(s.id));

  return pool.sort((a, b) => {
    const aPin = pinned.includes(a.id) ? -100 : 0;
    const bPin = pinned.includes(b.id) ? -100 : 0;
    const aScore = (ratings[a.id]?.worked ?? 0) - (ratings[a.id]?.nope ?? 0);
    const bScore = (ratings[b.id]?.worked ?? 0) - (ratings[b.id]?.nope ?? 0);
    const aBoost = a.traitBoost.filter(t => traits.includes(t)).length;
    const bBoost = b.traitBoost.filter(t => traits.includes(t)).length;
    return (aPin - bPin) || (bScore - aScore) || (bBoost - aBoost);
  });
}

/** Swallow the Frog: surface action-forward strategies first */
export function applyFrogFilter(strategies: Strategy[]): Strategy[] {
  const frogTags = new Set(['game', 'organize', 'quick']);
  return [
    ...strategies.filter(s => frogTags.has(s.tag)),
    ...strategies.filter(s => !frogTags.has(s.tag)),
  ];
}

/** Easy Win: surface low-barrier, reflective strategies first */
export function applyEasyWinFilter(strategies: Strategy[]): Strategy[] {
  const easyTags = new Set(['quick', 'reflect', 'mindset']);
  return [
    ...strategies.filter(s => easyTags.has(s.tag)),
    ...strategies.filter(s => !easyTags.has(s.tag)),
  ];
}
